//RENDER KEYBOARD

import { Button } from "../index";

///render key Row
const renderKeyboardRow = (arrobject, parent) => {
  arrobject.forEach((objectSettings) => {
    let newButton = new Button(objectSettings);
    newButton.createButton(parent);
  });
};

//render Key Board
const renderKeyBoard = () => {
  let arrobject1 = [
    {
      keyEn: "§",
      keyEnUp: "±",
      keyRu: ">",
      keyRuUp: "<",
      code: "Backquote",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "1",
      keyEnUp: "!",
      keyRu: "1",
      keyRuUp: "!",
      code: "Digit1",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "2",
      keyEnUp: "@",
      keyRu: "2",
      keyRuUp: '"',
      code: "Digit2",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "3",
      keyEnUp: "#",
      keyRu: "3",
      keyRuUp: "№",
      code: "Digit3",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "4",
      keyEnUp: "$",
      keyRu: "4",
      keyRuUp: "%",
      code: "Digit4",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "5",
      keyEnUp: "%",
      keyRu: "5",
      keyRuUp: ":",
      code: "Digit5",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "6",
      keyEnUp: "^",
      keyRu: "6",
      keyRuUp: ",",
      code: "Digit6",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "7",
      keyEnUp: "&",
      keyRu: "7",
      keyRuUp: ".",
      code: "Digit7",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "8",
      keyEnUp: "*",
      keyRu: "8",
      keyRuUp: ";",
      code: "Digit8",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "9",
      keyEnUp: "(",
      keyRu: "9",
      keyRuUp: "(",
      code: "Digit9",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "0",
      keyEnUp: ")",
      keyRu: "0",
      keyRuUp: ")",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "-",
      keyEnUp: "_",
      keyRu: "-",
      keyRuUp: "_",
      code: "NumpadSubstract",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "=",
      keyEnUp: "+",
      keyRu: "=",
      keyRuUp: "+",
      code: "Equal",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "Backspace",
      keyEnUp: "Backspace",
      keyRu: "Backspace",
      keyRuUp: "Backspace",
      code: "Backspace",
      width: "110px",
      color: "blue",
    },
  ];
  let arrobject2 = [
    {
      keyEn: "Tab",
      keyEnUp: "Tab",
      keyRu: "Tab",
      keyRuUp: "Tab",
      code: "Tab",
      width: "55px",
      color: "blue",
    },
    {
      keyEn: "q",
      keyEnUp: "Q",
      keyRu: "й",
      keyRuUp: "Й",
      code: "KeyQ",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "w",
      keyEnUp: "W",
      keyRu: "ц",
      keyRuUp: "Ц",
      code: "KeyW",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "e",
      keyEnUp: "E",
      keyRu: "у",
      keyRuUp: "У",
      code: "KeyE",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "r",
      keyEnUp: "R",
      keyRu: "к",
      keyRuUp: "К",
      code: "KeyR",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "t",
      keyEnUp: "T",
      keyRu: "е",
      keyRuUp: "Е",
      code: "KeyT",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "y",
      keyEnUp: "Y",
      keyRu: "н",
      keyRuUp: "Н",
      code: "KeyY",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "u",
      keyEnUp: "U",
      keyRu: "г",
      keyRuUp: "Г",
      code: "KeyU",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "i",
      keyEnUp: "I",
      keyRu: "ш",
      keyRuUp: "Ш",
      code: "KeyI",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "o",
      keyEnUp: "O",
      keyRu: "щ",
      keyRuUp: "Щ",
      code: "KeyO",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "p",
      keyEnUp: "P",
      keyRu: "з",
      keyRuUp: "З",
      code: "KeyP",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "[",
      keyEnUp: "{",
      keyRu: "х",
      keyRuUp: "Х",
      code: "BracketLeft",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "]",
      keyEnUp: "}",
      keyRu: "ъ",
      keyRuUp: "Ъ",
      code: "BracketRight",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "\\",
      keyEnUp: "|",
      keyRu: "ё",
      keyRuUp: "Ё",
      code: "Backslash",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "Delete",
      keyEnUp: "Delete",
      keyRu: "Delete",
      keyRuUp: "Delete",
      code: "Delete",
      width: "50px",
      color: "blue",
    },
  ];
  let arrobject3 = [
    {
      keyEn: "CapsLock",
      keyEnUp: "CapsLock",
      keyRu: "CapsLock",
      keyRuUp: "CapsLock",
      code: "CapsLock",
      width: "115px",
      color: "blue",
    },
    {
      keyEn: "a",
      keyEnUp: "A",
      keyRu: "ф",
      keyRuUp: "Ф",
      code: "KeyA",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "s",
      keyEnUp: "S",
      keyRu: "ы",
      keyRuUp: "Ы",
      code: "KeyS",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "d",
      keyEnUp: "D",
      keyRu: "в",
      keyRuUp: "В",
      code: "KeyD",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "f",
      keyEnUp: "F",
      keyRu: "а",
      keyRuUp: "А",
      code: "KeyF",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "g",
      keyEnUp: "G",
      keyRu: "п",
      keyRuUp: "П",
      code: "KeyG",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "h",
      keyEnUp: "H",
      keyRu: "р",
      keyRuUp: "Р",
      code: "KeyH",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "j",
      keyEnUp: "J",
      keyRu: "о",
      keyRuUp: "О",
      code: "KeyJ",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "k",
      keyEnUp: "K",
      keyRu: "л",
      keyRuUp: "Л",
      code: "KeyK",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "l",
      keyEnUp: "L",
      keyRu: "д",
      keyRuUp: "Д",
      code: "KeyL",
      width: "50px",
      color: "black",
    },
    {
      keyEn: ";",
      keyEnUp: ":",
      keyRu: "ж",
      keyRuUp: "Ж",
      code: "Semicolon",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "'",
      keyEnUp: '"',
      keyRu: "э",
      keyRuUp: "Э",
      code: "Quote",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "Enter",
      keyEnUp: "Enter",
      keyRu: "Enter",
      keyRuUp: "Enter",
      code: "Enter",
      width: "115px",
      color: "blue",
    },
  ];
  let arrobject4 = [
    {
      keyEn: "Shift",
      keyEnUp: "Shift",
      keyRu: "Shift",
      keyRuUp: "Shift",
      code: "ShiftLeft",
      width: "110px",
      color: "blue",
    },
    {
      keyEn: "`",
      keyEnUp: "~",
      keyRu: "]",
      keyRuUp: "[",
      code: "IntlBackslash",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "z",
      keyEnUp: "Z",
      keyRu: "я",
      keyRuUp: "Я",
      code: "KeyZ",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "x",
      keyEnUp: "X",
      keyRu: "ч",
      keyRuUp: "Ч",
      code: "KeyX",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "c",
      keyEnUp: "C",
      keyRu: "с",
      keyRuUp: "С",
      code: "KeyC",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "v",
      keyEnUp: "V",
      keyRu: "м",
      keyRuUp: "М",
      code: "KeyV",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "b",
      keyEnUp: "B",
      keyRu: "и",
      keyRuUp: "И",
      code: "KeyB",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "n",
      keyEnUp: "N",
      keyRu: "т",
      keyRuUp: "Т",
      code: "KeyN",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "m",
      keyEnUp: "M",
      keyRu: "ь",
      keyRuUp: "Ь",
      code: "KeyM",
      width: "50px",
      color: "black",
    },
    {
      keyEn: ",",
      keyEnUp: "<",
      keyRu: "б",
      keyRuUp: "Б",
      code: "Comma",
      width: "50px",
      color: "black",
    },
    {
      keyEn: ".",
      keyEnUp: ">",
      keyRu: "ю",
      keyRuUp: "Ю",
      code: "Period",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "/",
      keyEnUp: "?",
      keyRu: "/",
      keyRuUp: "?",
      code: "Slash",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "\u2191",
      keyEnUp: "\u2191",
      keyRu: "\u2191",
      keyRuUp: "\u2191",
      code: "ArrowUp",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "Shift",
      keyEnUp: "Shift",
      keyRu: "Shift",
      keyRuUp: "Shift",
      code: "ShiftRight",
      width: "50px",
      color: "blue",
    },
  ];
  let arrobject5 = [
    {
      keyEn: "Control",
      keyEnUp: "Control",
      keyRu: "Control",
      keyRuUp: "Control",
      code: "Control",
      width: "55px",
      color: "blue",
    },
    {
      keyEn: "Alt",
      keyEnUp: "Alt",
      keyRu: "Alt",
      keyRuUp: "Alt",
      code: "AltLeft",
      width: "50px",
      color: "blue",
    },
    {
      keyEn: "Cmd",
      keyEnUp: "Cmd",
      keyRu: "Cmd",
      keyRuUp: "Cmd",
      code: "MetaLeft",
      width: "50px",
      color: "blue",
    },
    {
      keyEn: "Space",
      keyEnUp: "Space",
      keyRu: "Space",
      keyRuUp: "Space",
      code: "Space",
      width: "380px",
      color: "black",
    },
    {
      keyEn: "Cmd",
      keyEnUp: "Cmd",
      keyRu: "Cmd",
      keyRuUp: "Cmd",
      code: "MetaRight",
      width: "50px",
      color: "blue",
    },
    {
      keyEn: "Alt",
      keyEnUp: "Alt",
      keyRu: "Alt",
      keyRuUp: "Alt",
      code: "AltRight",
      width: "50px",
      color: "blue",
    },
    {
      keyEn: "\u2190",
      keyEnUp: "\u2190",
      keyRu: "\u2190",
      keyRuUp: "\u2190",
      code: "ArrowLeft",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "\u2193",
      keyEnUp: "\u2193",
      keyRu: "\u2193",
      keyRuUp: "\u2193",
      code: "ArrowDown",
      width: "50px",
      color: "black",
    },
    {
      keyEn: "\u2192",
      keyEnUp: "\u2192",
      keyRu: "\u2192",
      keyRuUp: "\u2192",
      code: "ArrowRight",
      width: "50px",
      color: "black",
    },
  ];
  for (let i = 1; i <= 5; i++) {
    let parent = document.createElement("div");
    parent.className = "row-wrapper";
    parent.id = "keyboard-row";
    document.querySelector("#keyboard-wrapper").append(parent);
    renderKeyboardRow(eval("arrobject" + i), parent);
  }
};

export { renderKeyBoard };
